# Generated by Django 2.2.28 on 2023-10-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_English_name', models.CharField(max_length=250, unique=True)),
                ('Category_Arabic_name', models.CharField(max_length=250, unique=True)),
                ('categoryslug', models.SlugField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Categories')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englishName', models.CharField(max_length=100)),
                ('arabicName', models.CharField(max_length=100)),
                ('subCategoryslug', models.SlugField(blank=True, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories_and_products.Category')),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('product_english_name', models.CharField(blank=True, max_length=250, null=True)),
                ('product_arabic_name', models.CharField(blank=True, max_length=250, null=True)),
                ('country_of_manufacturing', models.CharField(blank=True, max_length=250, null=True)),
                ('importer_name', models.CharField(blank=True, max_length=250, null=True)),
                ('franchise', models.BooleanField(default=False)),
                ('range_of_prices', models.CharField(blank=True, max_length=250, null=True)),
                ('year_of_import', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('productslug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('avoid', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories_and_products.Category')),
                ('subCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories_and_products.SubCategory')),
            ],
        ),
    ]
