# Generated by Django 4.2.6 on 2023-10-20 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0004_alter_category_id_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories_and_products.category'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
