# Generated by Django 4.2.6 on 2023-10-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0006_rename_subcategory_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
