# Generated by Django 4.2.6 on 2023-10-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0007_remove_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_existence',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productslug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
