# Generated by Django 4.2.6 on 2023-11-03 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0010_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories_and_products.sector'),
        ),
    ]
