# Generated by Django 4.2.6 on 2023-11-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_and_products', '0011_category_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='Sub_Category_Arabic_name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='Sub_Category_English_name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
