# Generated by Django 4.2.7 on 2023-11-07 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories_and_products", "0014_alter_product_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=50)),
                ("importance", models.FloatField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories_and_products.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["keyword"], name="categories__keyword_8a3a78_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="keyword",
            constraint=models.UniqueConstraint(
                fields=("keyword", "product"), name="unique_keyword"
            ),
        ),
    ]
