# Generated by Django 4.2.7 on 2023-11-07 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories_and_products", "0015_keyword_keyword_unique_keyword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="categories_and_products.product",
            ),
        ),
    ]
