# Generated by Django 4.2.7 on 2023-11-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories_and_products", "0017_delete_keyword"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "english_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "arabic_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(to="categories_and_products.tags"),
        ),
    ]
