# Generated by Django 4.2.7 on 2023-11-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories_and_products", "0018_tags_product_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name_plural": "Tags"},
        ),
        migrations.AlterField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(
                blank=True, null=True, to="categories_and_products.tags"
            ),
        ),
    ]
