# Generated by Django 4.2.7 on 2023-11-09 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "categories_and_products",
            "0019_alter_product_options_alter_tags_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_english_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "product_arabic_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "country_of_existence",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("image", models.FileField(upload_to="uploads/user_uploads/")),
                ("user_tags", models.CharField(blank=True, max_length=250, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("pending", models.BooleanField(default=True)),
                ("publish", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Uploads",
            },
        ),
    ]
