# Generated by Django 4.2.7 on 2023-11-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories_and_products", "0021_alter_product_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userupload",
            name="image",
            field=models.FileField(upload_to="user_uploads/"),
        ),
    ]
