# Generated by Django 4.2.7 on 2023-11-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories_and_products", "0023_userupload_serial_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userupload",
            name="image",
            field=models.ImageField(upload_to="user_uploads/"),
        ),
    ]
