# Generated by Django 4.2.7 on 2023-11-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories_and_products", "0024_alter_userupload_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userupload",
            name="country_of_existence",
        ),
        migrations.AddField(
            model_name="product",
            name="serial_number",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="userupload",
            name="image",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
