# Generated by Django 4.2.7 on 2023-11-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories_and_products", "0026_remove_product_productslug_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rate",
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rate",
            field=models.FloatField(blank=True, default=0.0, max_length=5, null=True),
        ),
    ]
